from fpdf import FPDF
import re
import os
from datetime import datetime


class ReportPDF(FPDF):
    def __init__(self, topic):
        super().__init__()
        self.topic = topic
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, f"AI Research Report: {self.topic[:60]}", align="L")
        self.ln(2)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by AI Research Agent | {datetime.now().strftime('%Y-%m-%d')} | Page {self.page_no()}", align="C")


def export_report_to_pdf(report_text: str, topic: str, output_dir: str = "reports") -> str:
    os.makedirs(output_dir, exist_ok=True)

    safe_topic = re.sub(r'[^\w\s-]', '', topic).strip().replace(' ', '_')[:40]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{output_dir}/report_{safe_topic}_{timestamp}.pdf"

    pdf = ReportPDF(topic)
    pdf.add_page()

    lines = report_text.split("\n")

    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue

        if line.startswith("# ") and not line.startswith("## "):
            title = line[2:].strip()
            pdf.set_font("Helvetica", "B", 18)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 10, title)
            pdf.ln(4)

        elif line.startswith("## "):
            heading = line[3:].strip()
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(40, 80, 140)
            pdf.multi_cell(0, 8, heading)
            pdf.set_draw_color(40, 80, 140)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)

        elif line.startswith("### "):
            subheading = line[4:].strip()
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 7, subheading)
            pdf.ln(1)

        elif line.startswith("- ") or line.startswith("* "):
            content = line[2:].strip()
            content = re.sub(r'\*\*(.*?)\*\*', r'\1', content)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(6)
            pdf.multi_cell(0, 6, f"• {content}")

        else:
            clean = re.sub(r'\*\*(.*?)\*\*', r'\1', line)
            clean = re.sub(r'\*(.*?)\*', r'\1', clean)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, clean)
            pdf.ln(1)

    pdf.output(filename)
    return filename
